import os
from pathlib import Path
from enum import Enum

# --- Monorepo Path Resolution ---
BASE_DIR = Path(__file__).resolve().parent.parent

SHARED_CONFIG_DIR = Path(os.getenv("SHARED_CONFIG_DIR", BASE_DIR / "shared_config"))
SHARED_SECRETS_DIR = Path(os.getenv("SHARED_SECRETS_DIR", BASE_DIR / "shared_secrets"))
SHARED_DATA_DIR = Path(os.getenv("SHARED_DATA_DIR", BASE_DIR / "shared_data"))

class SystemFlag(str, Enum):
    """
    Centralized dictionary of all System Flags generated by The Auditor.
    Using an Enum prevents typo-induced bugs and provides self-documenting code.
    """
    OK = "OK"
    
    # Discord Sync Flags
    NOT_IN_DISCORD = "Not in Discord"  # Member exists in the DB but is missing from the Discord Server.
    
    # Audit Logic Flags
    RANK_MISMATCH = "Rank Mismatch"    # The member's Discord Roles do not align with their assigned Clan Rank.
    NOT_IN_WOM_CLAN = "Not in WOM Clan"  # The member's tracked WOM accounts are no longer in the target WOM group.
    BANNED_IN_CLAN = "Banned in Clan"  # Tracked WOM account is banned but still in the WOM group.
    MISSING_RSNS = "Missing RSNs"      # Member has a clan rank or discord role, but 0 linked accounts.
    MULTIPLE_CLANS = "Multiple Clans"  # Member is in the target clan, but also in other clans.
    ARCHIVED = "Archived"              # The member has no clan rank, no managed discord roles, and is not in the WOM clan.